#!/usr/bin/env bash
# Generates the `cohort-starter` branch: R1 + R2 + R3a only, from the current
# `main` reference build. Reproducible and re-runnable — this script IS the
# documentation of exactly what is excluded and why, not a one-off hand edit.
#
# Rationale (see docs/DEV_PLAN/DECISIONS/R6-DEFERRED-STUDENT-OWNED.md and
# docs/DEV_PLAN/PHASE-R-CLOSURE-AND-COHORT-HANDOFF-REPORT.md §3): R1/R2/R3a
# were committed together with R3b/R4/R5/R7 in one combined commit
# (47b46de5) for practical reasons at the time — there is no clean git
# history point to check out "just the walking skeleton" from. This script
# reconstructs that state by explicit deletion + trimming, not by pretending
# a clean historical commit exists.
#
# Safe by construction: runs entirely on a local branch, never pushes,
# never touches `main`, never touches `ttod.yml`/`schema/`/`ttod_core/`.
#
# Usage: bash scripts/generate-cohort-starter.sh
# Re-run any time `main`'s reference build changes and the starter needs to
# be regenerated — delete the local `cohort-starter` branch first if it
# already exists (the script will refuse to overwrite it silently).

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

BRANCH=cohort-starter
BASE_REF=main

if git show-ref --verify --quiet "refs/heads/$BRANCH"; then
  echo "REFUSED: branch '$BRANCH' already exists locally." >&2
  echo "Delete it first if you intend to regenerate: git branch -D $BRANCH" >&2
  exit 1
fi

if [ -n "$(git status --porcelain)" ]; then
  echo "REFUSED: working tree is not clean. Commit or stash before generating." >&2
  exit 1
fi

echo "== Creating $BRANCH from $BASE_REF =="
git checkout -b "$BRANCH" "$BASE_REF"

echo "== Removing R3b/R4/R5/R7 reference-only frontend source =="
rm -rf \
  services/frontend/src/content.config.ts \
  services/frontend/src/content \
  services/frontend/src/pages/'[locale]'/docs \
  services/frontend/src/pages/'[locale]'/wisdom \
  services/frontend/src/pages/'[locale]'/graph.astro \
  services/frontend/src/pages/'[locale]'/oracle.astro \
  services/frontend/src/components/graph \
  services/frontend/src/components/oracle \
  services/frontend/src/lib/db.ts \
  services/frontend/src/styles/tokens.css \
  services/frontend/tailwind.config.mjs

echo "== Removing reference-only reports and R7's reference-build test artifacts =="
rm -f \
  docs/DEV_PLAN/PHASE-R3b-REPORT.md \
  docs/DEV_PLAN/PHASE-R4-REPORT.md \
  docs/DEV_PLAN/PHASE-R5-REPORT.md \
  docs/DEV_PLAN/PHASE-R7-REPORT.md \
  docs/testing-strategy.md \
  tests/test_r7_platform.py \
  tests/fixtures/r_oracle_threshold_calibration.json \
  tests/fixtures/r_negative_oracle_propose_no_active.json

echo "== Trimming astro.config.mjs (MDX + Tailwind belong to R3b, not R3a) =="
cat > services/frontend/astro.config.mjs <<'EOF'
import { defineConfig } from 'astro/config';
import node from '@astrojs/node';
import react from '@astrojs/react';
import svelte from '@astrojs/svelte';

export default defineConfig({
  output: 'server',
  adapter: node({ mode: 'standalone' }),
  integrations: [react(), svelte()],
  i18n: {
    locales: ['en', 'es'],
    defaultLocale: 'en',
    routing: { prefixDefaultLocale: true }
  },
  server: { host: true, port: 4321 }
});
EOF

echo "== Trimming package.json (removing R3b/R4/R5-only dependencies) =="
node -e '
const fs = require("fs");
const path = "services/frontend/package.json";
const pkg = JSON.parse(fs.readFileSync(path, "utf8"));
const remove = ["@astrojs/mdx", "@tailwindcss/typography", "@tailwindcss/vite", "tailwindcss", "framer-motion", "gsap"];
for (const dep of remove) delete pkg.dependencies[dep];
// npm may omit target-platform optional packages when this lockfile is generated
// on macOS (npm/cli#4828). The starter is built in Linux-musl containers on both
// x64 Lilith and arm64 developer machines, so make those build dependencies
// explicit instead of trusting an implicit transitive lockfile entry.
pkg.optionalDependencies = {
  ...(pkg.optionalDependencies ?? {}),
  "@rollup/rollup-linux-arm64-musl": "4.63.1",
  "@rollup/rollup-linux-x64-musl": "4.63.1"
};
fs.writeFileSync(path, JSON.stringify(pkg, null, 2) + "\n");
'

echo "== Regenerating package-lock.json against the trimmed manifest =="
( cd services/frontend && rm -f package-lock.json && npm install --package-lock-only )

echo "== Regenerating INDEX.md and master cascade status for the starter's own history =="
# The starter branch keeps R0-R3a's own reports/runbooks (R1, R2, R3a are DONE
# and instructor-owned regardless of which branch a student is on) but must
# not claim R3b-R7 exist on this branch.
python3 - <<'PYEOF'
import pathlib
p = pathlib.Path("docs/DEV_PLAN/INDEX.md")
text = p.read_text()
marker = "\n\n---\n\n## Cohort-starter branch note\n"
if marker not in text:
    text += (
        marker
        + "This is the `cohort-starter` branch, generated by "
        + "`scripts/generate-cohort-starter.sh` from `main` — see "
        + "`docs/DEV_PLAN/DECISIONS/R6-DEFERRED-STUDENT-OWNED.md`. It contains R1/R2/R3a "
        + "(DONE, instructor-built walking skeleton) and every R1-R7 runbook, but none of "
        + "R3b/R4/R5/R7's reference-build source — those exist only on `main`, as a "
        + "reference/architectural-validation build, not the student deliverable. Build your "
        + "own R3b onward from `docs/DEV_PLAN/PHASES/R3b-astro-content-engine.md` onward.\n"
    )
    p.write_text(text)
PYEOF

echo "== Verifying the trimmed frontend actually builds =="
( cd services/frontend && npm install && ASTRO_TELEMETRY_DISABLED=1 npm run check && ASTRO_TELEMETRY_DISABLED=1 npm run build )

echo "== Committing the starter snapshot =="
git add -A
git commit -m "$(cat <<'EOF'
cohort-starter: R1/R2/R3a only, generated from main

Generated by scripts/generate-cohort-starter.sh — see
docs/DEV_PLAN/DECISIONS/R6-DEFERRED-STUDENT-OWNED.md for why this branch
exists and exactly what it excludes. Contains the instructor-built walking
skeleton (R1 backend, R2 FastMCP, R3a Astro shell) plus every R1-R7 runbook
so students can build R3b onward themselves. Excludes R3b/R4/R5/R7's
reference-build source and reports, tailwind/MDX/GSAP/Framer dependencies
those lanes introduced, and R7's reference-build-specific test artifacts.

Re-run the generation script against a future main if the reference build
changes and this branch needs regenerating — do not hand-edit this branch
to diverge from what the script produces.

Co-Authored-By: Claude Sonnet 5 <noreply@anthropic.com>
EOF
)"

echo "== Done. Currently on branch: $(git branch --show-current) =="
echo "Nothing was pushed. Verify with 'git log --oneline -3' and 'git diff main --stat',"
echo "then switch back with 'git checkout main' when done inspecting."
